name: GitHub Actions

on:
  schedule:
    - cron: '0 12 * * 1'
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    tags: '*'

permissions:
  contents: read

jobs:
  build_test:
    name: Run build test
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false
      - name: build test with container
        run:
          docker build . -t ezio_ci_test
